urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailsView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("add_question/", views.add_form, name="add_form"),
]

models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=500)
    pub_date  = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

forms.py
from django import forms
from .models import Question

class QuestionForm(forms.Form):
    question = forms.CharField(label="Question", max_length=500)
    choice_one = forms.CharField(label="Choice 1", max_length=200)
    choice_two = forms.CharField(label="Choice 2", max_length=200)

class QuestionModelForm(forms.ModelForm):
    choice_one = forms.CharField(label="Choice 1", max_length=200)
    choice_two = forms.CharField(label="Choice 2", max_length=200)
    class Meta:
        model = Question
        fields = ["question_text"]

views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
# from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic
from .models import Question, Choice
from .forms import QuestionForm, QuestionModelForm
from django.contrib import messages

# Create your views here.
class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"
    
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:10]

class DetailsView(generic.DetailView):
    model = Question
    template_name = "polls/details.html"

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/details.html", { "question": question, "error_message": "You didn't select a choice.",})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

def add_form(request):
    if request.method == "POST":
        form = QuestionModelForm(request.POST)
        if form.is_valid():
            ques = Question(question_text = form.cleaned_data['question_text'], pub_date = timezone.now())
            ques.save()
            # form.save()
            Choice(question=ques, choice_text = form.cleaned_data['choice_one'], votes=0).save()
            Choice(question=ques, choice_text = form.cleaned_data['choice_two'], votes=0).save()
            return HttpResponseRedirect(reverse("polls:index"))
        else:
            return HttpResponseRedirect(reverse("polls:index"))
    else:
        form = QuestionModelForm()
        return render(request, "polls/add_question.html", {"form": form})

templates/polls/add_question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Question - Polls</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/add.css' %}">
</head>
<body>
    <form action="{% url 'polls:add_form' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add" id="submit-btn">
    </form>
</body>
</html>

templates/polls/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details - Polls</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/details.css' %}">
</head>
<body>
    <a href="{% url 'polls:index' %}" class="home-btn">Home</a>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p class="err-msg"><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" class="radio-btn">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                <br>
                {% endfor %}
        </fieldset>
        <input type="submit" value="Vote" class="submit-btn">
    </form>
</body>
</html>

templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Polls Application</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
    <h2 class="super-title">Polls List</h2>
    <section class="container">
        {% if latest_question_list %}
        {% for question in latest_question_list %}
        <a href="{% url 'polls:detail' question.id %}"><div class="question-tab">
            <h2>
                {{ question.question_text }}
            </h2>
            <p>&dash; {{ question.pub_date }}</p>
        </div></a>
        {% endfor %}
        {% else %}
        <p>No polls are available.</p>
        {% endif %}
    </section>
    <a href="{% url 'polls:add_form' %}" id="add_question_btn">Add Question</a>
</body>
</html>

templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results - Poll</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/results.css' %}">
</head>
<body>
    <a href="{% url 'polls:index' %}" class="home-btn">Home</a>
    <div>
        <h1>{{ question.question_text }}</h1>
        <ul>
            {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} &dash; <span>{{ choice.votes }} vote{{ choice.votes|pluralize }}</span></li>
            {% endfor %}
        </ul>
        <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
    </div>
</body>
</html>